services:
  artemis:
    image: apache/activemq-artemis:latest-alpine
    container_name: artemis
    environment:
      ARTEMIS_USER: artemis
      ARTEMIS_PASSWORD: artemis
      ANONYMOUS_LOGIN: "false"
    ports:
      - "61616:61616"
      - "8161:8161"
    volumes:
      - artemis-data:/var/lib/artemis-instance

volumes:
  artemis-data:
